立ち上げスクリプトの修正

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -10,7 +10,7 @@ done
 
 shift $((OPTIND - 1))
 
-# Configuration variables
+#環境変数の設定
 CONTAINER_NAME="database"
 DATABASE_NAME="school_db"
 NETWORK_NAME="school_app"
@@ -22,18 +22,31 @@ cd "$(dirname ${0})/.."
 eval "echo \"$(cat services/api/env.template)\"" > services/api/.env
 eval "echo \"$(cat services/client/env.template)\"" > services/client/.env
 
-
-
-# Create Docker network if it doesn't exist
+#Dockerネットワークなければ作成
 echo "Creating Docker network '$NETWORK_NAME' if not exists..."
 docker network ls | grep -wq $NETWORK_NAME || docker network create $NETWORK_NAME
 
 if [ -n "$FLG_DATABASE" ]; then
-    # Start the database container
+    #データベースコンテナがなければ作成
     echo "Starting the database container..."
     docker-compose -f docker-compose.db.yml up -d
 
-    # Create the database if it doesn't exist
+    #接続確認
+    echo "Waiting for PostgreSQL to be ready..."
+    RETRY_COUNT=0
+    MAX_RETRIES=5
+    until docker exec $CONTAINER_NAME pg_isready -U postgres || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
+        echo "PostgreSQL not ready, retrying in 2 seconds..."
+        sleep 2
+        RETRY_COUNT=$((RETRY_COUNT + 1))
+    done
+
+    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+        echo "Failed to connect to PostgreSQL after multiple attempts. Exiting..."
+        exit 1
+    fi
+
+    #データベースをなければ作成
     echo "Creating the database '$DATABASE_NAME'..."
     docker exec $CONTAINER_NAME psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $DATABASE_NAME
     if [ $? -eq 1 ]; then
@@ -42,26 +55,24 @@ if [ -n "$FLG_DATABASE" ]; then
     fi
 fi
 
-
 cd services/api
 
-# Set up Poetry environment
+# Set up the virtual environment with Poetry
 echo "Setting up the virtual environment with Poetry..."
 poetry env use python3
 poetry install --no-interaction --no-ansi
 
-# Apply database migrations
+#データベースマイグレーション
 echo "Running database migrations..."
 poetry run python manage.py migrate
 
-# Collect static files
+#Django の 静的ファイル収集
 echo "Collecting static files..."
 poetry run python manage.py collectstatic --noinput
 
-# Start the Django development server
+#開発サーバー起動
 echo "Starting the Django development server..."
 poetry run python manage.py runserver 0.0.0.0:8000 &
-
 
 cd ../client
 
